export const TAGLOADING = 'TAGLOADING';
export const TAGLISTSUCCESS = 'TAGLISTSUCCESS';
export const TAGTFAILED = 'TAGTFAILED';


export const PROMOTIONLOADING = 'PROMOTIONLOADING';
export const PROMOTIONLISTSUCCESS = 'PROMOTIONLISTSUCCESS';
export const PROMOTIONFAILED = 'PROMOTIONFAILED';


export const PROMOTIONDETAILLOADING = 'PROMOTIONDETAILLOADING';
export const PROMOTIONDETAILLISTSUCCESS = 'PROMOTIONDETAILLISTSUCCESS';
export const PROMOTIONDETAILFAILED = 'PROMOTIONDETAILFAILED';